import Link from "next/link";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="flex gap-2  bg-slate-900 text-white">
          <Link className="hover:bg-green-500 p-5" href={"/"}>Home</Link>
          <Link className=" hover:bg-green-500 p-5" href={"/blog"}>Blog</Link>
          <Link className=" hover:bg-green-500 p-5" href={"/order-product"}>Order-product</Link>
          <Link className=" hover:bg-green-500 p-5" href={"/dashboard-with-parallel-routes"}>Dashboard-With-Parallel-Routes</Link>
          <Link className=" hover:bg-green-500 p-5" href={"/profile"}>Profile</Link>
          <Link className=" hover:bg-green-500 p-5" href={"/about"}>About</Link>
          <Link className=" hover:bg-green-500 p-5" href={"/product"}>Product</Link>
        </header>
        {children}
        <footer className="bg-teal-600 p-5">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
